import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/context/AuthContext";
import { QueryProvider } from "@/lib/react-query/QueryProvider"; // Import QueryProvider


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        {/* <AuthProvider>{children}</AuthProvider> */}

        <QueryProvider> 
        {children}
        </QueryProvider>

      </body>
    </html>
  );
}
